In [1]:
!pip install comtradeapicall

Collecting comtradeapicall
  Downloading comtradeapicall-1.2.1-py3-none-any.whl (19 kB)
Installing collected packages: comtradeapicall
Successfully installed comtradeapicall-1.2.1

In [2]:
import pandas as pd
import requests
import comtradeapicall
import time
import random
from IPython.display import clear_output
import os

subscription_key = '6739db54ee2542979dbc92a71e8ecc45' # kb9268@gmail.com  153844 + 61679
#subscription_key = '4f6f20402909438ab097877b243c130d' # sesame.park@gmail.com  91563 + 82402

directory = 'Z:\\14.Python\\python_tool\\UnComtradeAPI'  # output directory for downloaded files 
proxy_url = '<PROXY URL>'  # optional if you need proxy url

In [3]:
directory = 'data/UnOre/'  # output directory for downloaded files

# 조회조건

In [9]:
#hscode = '282540,283324' # 산화/수산화니켈(282540), 황산니켈(283324)

hscode = '282200,283329' # 산화/수산화코발트(282200), 황산코발트(283329)
#hscode = '282520,283691' # 산화/수산화리튬(282520), 탄산리튬(283691)
#hscode = '850610' # 이산화망간(850610)

flow_code = 'M,X' # M : Import / X : Export
total_period = '202404'

### Subscription key 필요없는 일부 데이터 확인용 코드

In [ ]:
mydf = comtradeapicall.previewFinalData(typeCode='C', freqCode='M', clCode='HS', period=total_period,
                                        reporterCode=None, cmdCode=hscode, flowCode=flow_code, partnerCode=None,
                                        partner2Code=None,
                                        customsCode=None, motCode=None, maxRecords=50000, format_output='JSON',
                                        aggregateBy=None, breakdownMode='classic', countOnly=None, includeDesc=True)
mydf

### Subscription key 필요한 다운로드 코드
* **너무 자주, 많이 호출하면 밴당할 수 있음**
* 조회조건 입력은 연단위, 월단위 중 하나만 실행

In [53]:
# CSV파일 저장(1개월씩 저장)
mydf = comtradeapicall.getFinalData(subscription_key, typeCode='C', freqCode='M', clCode='HS', period=total_period,
                                        reporterCode=None, cmdCode=hscode, flowCode=flow_code, partnerCode=None,
                                        partner2Code=None,
                                        customsCode=None, motCode=None, maxRecords='250000', format_output='JSON',
                                        aggregateBy=None, breakdownMode='classic', countOnly=None, includeDesc=True)

In [56]:
mydf

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate
0,C,M,20240401,2024,4,202404,36,AUS,Australia,M,...,4750.00,False,0.00,False,78240.053,76874.521,78240.053,0,False,True
1,C,M,20240401,2024,4,202404,36,AUS,Australia,M,...,4000.00,False,0.00,False,65844.782,64799.402,65844.782,0,False,True
2,C,M,20240401,2024,4,202404,36,AUS,Australia,M,...,750.00,False,0.82,False,12395.271,12075.119,12395.271,0,False,True
3,C,M,20240401,2024,4,202404,56,BEL,Belgium,M,...,365570.14,False,0.00,False,5848345.079,NaN,5848345.079,0,False,True
4,C,M,20240401,2024,4,202404,56,BEL,Belgium,M,...,4205.93,False,0.00,False,64881.997,NaN,64881.997,0,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1434,C,M,20240401,2024,4,202404,842,USA,USA,X,...,NaN,False,0.00,False,NaN,11900.000,11900.000,0,True,False
1435,C,M,20240401,2024,4,202404,842,USA,USA,X,...,NaN,False,0.00,False,NaN,71485.000,71485.000,0,True,False
1436,C,M,20240401,2024,4,202404,842,USA,USA,X,...,NaN,False,0.00,False,NaN,158392.000,158392.000,0,True,False
1437,C,M,20240401,2024,4,202404,842,USA,USA,X,...,52337.00,False,0.00,False,NaN,31402.000,31402.000,0,True,False
1438,C,M,20240401,2024,4,202404,842,USA,USA,X,...,NaN,False,0.00,False,NaN,15200.000,15200.000,0,True,False

In [ ]:
mydf.to_csv(f'{hscode}_{period_manual}.csv', index=False)
mydf

In [55]:
len(mydf)

1439

In [51]:
# list data availabity from last week for reference year 2021
mydf = comtradeapicall.getFinalDataAvailability(subscription_key, typeCode='C', freqCode='A', clCode='HS', period='2023',
                                        reporterCode=None, )

In [52]:
mydf

,datasetCode,typeCode,freqCode,period,reporterCode,reporterISO,reporterDesc,classificationCode,classificationSearchCode,isOriginalClassification,isExtendedFlowCode,isExtendedPartnerCode,isExtendedPartner2Code,isExtendedCmdCode,isExtendedCustomsCode,isExtendedMotCode,totalRecords,datasetChecksum,firstReleased,lastReleased
0,20020202301202100,C,A,2023,20,AND,Andorra,H6,HS,True,True,True,False,True,False,False,44414,-2141459391,2024-02-26T20:59:34.37,2024-02-26T20:59:34.37
1,20028202301082100,C,A,2023,28,ATG,Antigua and Barbuda,H3,HS,True,True,True,False,True,True,True,231162,-872960704,2024-03-14T20:59:54.8133333,2024-08-14T18:07:17.5233333
2,20031202301202100,C,A,2023,31,AZE,Azerbaijan,H6,HS,True,True,True,True,True,True,True,1236064,1500897420,2024-02-22T00:43:38.2566667,2024-02-22T00:43:38.2566667
3,20032202301182100,C,A,2023,32,ARG,Argentina,H5,HS,True,True,True,True,True,False,False,407890,1017738696,2024-04-04T17:48:27.8433333,2024-04-04T17:48:27.8433333
4,20036202301202100,C,A,2023,36,AUS,Australia,H6,HS,True,True,True,False,True,False,True,678496,-1405316983,2024-02-07T18:11:49.53,2024-02-07T18:11:49.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,20842202301202100,C,A,2023,842,USA,USA,H6,HS,True,True,True,False,True,False,False,1204648,1024585992,2024-02-11T05:48:29.3133333,2024-02-11T05:48:29.3133333
109,20854202301202100,C,A,2023,854,BFA,Burkina Faso,H6,HS,True,True,True,False,True,False,True,126996,1280313276,2024-03-06T20:43:47.7566667,2024-03-06T20:43:47.7566667
110,20858202301202100,C,A,2023,858,URY,Uruguay,H6,HS,True,True,True,False,True,True,True,479534,1135108942,2024-03-02T16:28:31.7,2024-03-02T16:28:31.7
111,20860202301202100,C,A,2023,860,UZB,Uzbekistan,H6,HS,True,True,True,False,True,False,False,193478,-1563949902,2024-07-25T16:58:23.09,2024-07-25T16:58:23.09
112,20894202301202100,C,A,2023,894,ZMB,Zambia,H6,HS,True,True,True,True,True,True,True,1371482,-182211165,2024-02-29T01:43:27.56,2024-02-29T01:43:27.56

In [53]:
# list data availabity from last week for reference year 2021
mydf = comtradeapicall.getFinalDataAvailability(subscription_key, typeCode='C', freqCode='M', clCode='HS', period='202306',
                                        reporterCode=None, )

In [54]:
mydf

,datasetCode,typeCode,freqCode,period,reporterCode,reporterISO,reporterDesc,classificationCode,classificationSearchCode,isOriginalClassification,isExtendedFlowCode,isExtendedPartnerCode,isExtendedPartner2Code,isExtendedCmdCode,isExtendedCustomsCode,isExtendedMotCode,totalRecords,datasetChecksum,firstReleased,lastReleased
0,30020202306202100,C,M,202306,20,AND,Andorra,H6,HS,True,True,True,False,True,False,False,17941,184088359,2023-10-01T21:31:26.8,2024-02-26T21:26:24.1766667
1,30028202306082100,C,M,202306,28,ATG,Antigua and Barbuda,H3,HS,True,True,True,False,True,True,True,67698,-1290147162,2024-08-08T02:00:45.1366667,2024-08-08T02:00:45.1366667
2,30031202306202100,C,M,202306,31,AZE,Azerbaijan,H6,HS,True,True,True,True,True,True,True,470158,-918886254,2023-08-29T22:35:18.1166667,2023-08-29T22:35:18.1166667
3,30032202306182100,C,M,202306,32,ARG,Argentina,H5,HS,True,True,True,True,True,False,False,164513,-635919941,2023-09-23T10:18:14.5066667,2023-09-26T15:14:26.44
4,30036202306202100,C,M,202306,36,AUS,Australia,H6,HS,True,True,True,False,True,False,True,304238,1793332030,2023-08-27T16:50:36.25,2024-02-07T17:29:43.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,30842202306202100,C,M,202306,842,USA,USA,H6,HS,True,True,True,False,True,False,False,600064,1296895085,2023-08-23T04:07:05.9833333,2023-08-23T04:07:05.9833333
97,30854202306202100,C,M,202306,854,BFA,Burkina Faso,H6,HS,True,True,True,False,True,False,True,35321,1311604373,2024-03-06T23:03:01.6733333,2024-03-06T23:03:01.6733333
98,30858202306202100,C,M,202306,858,URY,Uruguay,H6,HS,True,True,True,False,True,True,True,184276,-1991811542,2024-03-02T16:34:52.41,2024-03-02T16:34:52.41
99,30860202306202100,C,M,202306,860,UZB,Uzbekistan,H6,HS,True,True,True,False,True,False,False,76445,2031758703,2023-12-25T02:48:00.8666667,2023-12-25T02:48:00.8666667
100,30894202306202100,C,M,202306,894,ZMB,Zambia,H6,HS,True,True,True,True,True,True,True,410463,-1120922069,2024-02-29T02:58:48.9866667,2024-02-29T02:58:48.9866667

In [40]:
# list data availabity from last week for reference year 2021
mydf = comtradeapicall._getFinalDataAvailability(subscription_key, typeCode='C', freqCode='M', clCode='HS', period='202407',
                                        reporterCode=None, )
mydf

TypeError: _getFinalDataAvailability() got multiple values for argument 'typeCode'

In [29]:
mydf['lastReleased'].sort_values(ascending=False)

51         2024-09-14T04:11:24.75
59    2024-09-13T15:25:44.3066667
9     2024-09-11T21:25:47.7366667
53         2024-09-05T23:11:16.24
29         2024-09-04T21:06:25.84
                 ...
32         2024-06-21T20:59:10.19
61    2024-06-21T16:14:51.3266667
52    2024-06-11T23:42:58.2233333
41    2024-06-01T10:25:55.0166667
42    2024-05-23T07:45:14.2533333
Name: lastReleased, Length: 62, dtype: object